services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: txn-processing-app-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-3002}:${PORT:-3002}"
    networks:
      - assessment-development

networks:
  assessment-development:
    name: assessment-development
